config/routes.rb
Rails.application.routes.draw do
  get 'login' => 'sessions#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post 'login' => 'sessions#create'
  get "logout" => "sessions#destroy", as: "logout"

  root "to_buy#index"
  get "list_api" => "to_buy#list_api"


  get "auth/invite" => "invite#new" , as: "user_create"
  post "auth/invite" => "invite#create_temp" , as: "user_create_post"


  get 'auth/token/(:uuid)' , :to => "invite#check_token" 
  post 'auth/token/(:uuid)' , :to => "invite#create_user" , as: "real_user_create"


  post "delete" => "to_buy#delete"
  post "change" => "to_buy#change_done"
  get "new" => "to_buy#new" , as: "to_buy_new"
  post "create" => "to_buy#create"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Tobuys</title>
    <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <meta name="viewport" content="width=device-width, initial-scale=1">
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
            <%= stylesheet_link_tag 'application', media: 'all' %>
                <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
                <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
                <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
                <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
                <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>

                <%= javascript_pack_tag 'application' %>
                    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-info">
            <div class="container-fluid">
                <a class="navbar-brand " href="/">購入依頼リスト</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">

                    <!-- この下の行に mr-auto クラスを付与するだけ -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="/">購入依頼リスト</a>
                        </li>
                        <li class="nav-item">
                            <%= link_to "新規作成" ,to_buy_new_path ,class: "nav-link" , data: {"turbolinks" => false}%>
                        </li>

                    </ul>

                    <ul class="navbar-nav">

                        <% if logged_in?%>
                            <li class="nav-item">
                                <%= link_to "招待" ,user_create_path ,class: "nav-link" , data: {"turbolinks" => false}%>
                                    <a class="nav-link" href="/logout">logout</a>
                            </li>
                            <% else %>

                                <a class="nav-link dropdown-item" href="/login">Login</a>

                                <% end %>

                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <%= flash[:notice]%>
        <%= yield %>

</body>

</html>